// <auto-generated />
using System;
using Joana.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Joana.Infrastructure.Migrations
{
    [DbContext(typeof(JoanaDbContext))]
    [Migration("20260921112947_AddJeAktivnaToСenaProizvoda")]
    partial class AddJeAktivnaToСenaProizvoda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Joana.Domain.CenaProizvoda", b =>
                {
                    b.Property<int>("IdProizvod")
                        .HasColumnType("integer");

                    b.Property<int>("IdCena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdCena"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("JeAktivna")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasDefaultValue("aktivna");

                    b.HasKey("IdProizvod", "IdCena");

                    b.ToTable("CenaProizvoda");
                });

            modelBuilder.Entity("Joana.Domain.Kategorija", b =>
                {
                    b.Property<int>("IdKategorija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdKategorija"));

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdKategorija");

                    b.HasIndex("NazivKategorije")
                        .IsUnique();

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("Joana.Domain.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdKorisnik"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("IdKorisnik");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnik");

                    b.HasDiscriminator<string>("Role").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Joana.Domain.Narudzbenica", b =>
                {
                    b.Property<int>("IdNarudzbenica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdNarudzbenica"));

                    b.Property<int?>("AdministratorIdKorisnik")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DatumKreiranja")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("IdAdministrator")
                        .HasColumnType("integer");

                    b.Property<int>("IdKupac")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatusNarudzbenice")
                        .HasColumnType("integer");

                    b.Property<string>("NapomenaKupca")
                        .HasColumnType("text");

                    b.HasKey("IdNarudzbenica");

                    b.HasIndex("AdministratorIdKorisnik");

                    b.HasIndex("IdKupac");

                    b.HasIndex("IdStatusNarudzbenice");

                    b.ToTable("Narudzbenica");
                });

            modelBuilder.Entity("Joana.Domain.ObradaNarudžbenice", b =>
                {
                    b.Property<int>("IdObrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdObrada"));

                    b.Property<DateTimeOffset>("DatumObrada")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("IdAdministrator")
                        .HasColumnType("integer");

                    b.Property<int>("IdNarudzbenica")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatusNarudzbenica")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .HasColumnType("text");

                    b.HasKey("IdObrada");

                    b.HasIndex("IdAdministrator");

                    b.HasIndex("IdNarudzbenica");

                    b.HasIndex("IdStatusNarudzbenica");

                    b.ToTable("ObradaNarudžbenice");
                });

            modelBuilder.Entity("Joana.Domain.Proizvod", b =>
                {
                    b.Property<int>("IdProizvod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdProizvod"));

                    b.Property<int>("JedinicaMere")
                        .HasColumnType("integer");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("integer");

                    b.Property<int>("Lager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.HasKey("IdProizvod");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Joana.Domain.StatusNarudzbenice", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("NazivStatusa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusNarudzbenice");
                });

            modelBuilder.Entity("Joana.Domain.StavkaNarudzbenice", b =>
                {
                    b.Property<int>("IdNarudzbenica")
                        .HasColumnType("integer");

                    b.Property<int>("RBrProizvoda")
                        .HasColumnType("integer");

                    b.Property<int>("IdProizvod")
                        .HasColumnType("integer");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<decimal>("UgovorenaCena")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdNarudzbenica", "RBrProizvoda");

                    b.HasIndex("IdProizvod");

                    b.ToTable("StavkaNarudzbenice");
                });

            modelBuilder.Entity("Joana.Domain.Administrator", b =>
                {
                    b.HasBaseType("Joana.Domain.Korisnik");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("Joana.Domain.Kupac", b =>
                {
                    b.HasBaseType("Joana.Domain.Korisnik");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Kupac");
                });

            modelBuilder.Entity("Joana.Domain.CenaProizvoda", b =>
                {
                    b.HasOne("Joana.Domain.Proizvod", "Proizvod")
                        .WithMany("ListCenaProizvoda")
                        .HasForeignKey("IdProizvod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Joana.Domain.Narudzbenica", b =>
                {
                    b.HasOne("Joana.Domain.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorIdKorisnik");

                    b.HasOne("Joana.Domain.Kupac", "Kupac")
                        .WithMany("ListaNarudzbenica")
                        .HasForeignKey("IdKupac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joana.Domain.StatusNarudzbenice", "StatusNarudzbenice")
                        .WithMany()
                        .HasForeignKey("IdStatusNarudzbenice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Kupac");

                    b.Navigation("StatusNarudzbenice");
                });

            modelBuilder.Entity("Joana.Domain.ObradaNarudžbenice", b =>
                {
                    b.HasOne("Joana.Domain.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("IdAdministrator");

                    b.HasOne("Joana.Domain.Narudzbenica", "Narudzbenica")
                        .WithMany("ListObrada")
                        .HasForeignKey("IdNarudzbenica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joana.Domain.StatusNarudzbenice", "StatusNarudzbenica")
                        .WithMany()
                        .HasForeignKey("IdStatusNarudzbenica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Narudzbenica");

                    b.Navigation("StatusNarudzbenica");
                });

            modelBuilder.Entity("Joana.Domain.Proizvod", b =>
                {
                    b.HasOne("Joana.Domain.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("Joana.Domain.StavkaNarudzbenice", b =>
                {
                    b.HasOne("Joana.Domain.Narudzbenica", "Narudzbenica")
                        .WithMany("ListStavkeNarudzbenica")
                        .HasForeignKey("IdNarudzbenica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joana.Domain.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("IdProizvod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narudzbenica");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Joana.Domain.Narudzbenica", b =>
                {
                    b.Navigation("ListObrada");

                    b.Navigation("ListStavkeNarudzbenica");
                });

            modelBuilder.Entity("Joana.Domain.Proizvod", b =>
                {
                    b.Navigation("ListCenaProizvoda");
                });

            modelBuilder.Entity("Joana.Domain.Kupac", b =>
                {
                    b.Navigation("ListaNarudzbenica");
                });
#pragma warning restore 612, 618
        }
    }
}
