// <auto-generated />
using System;
using Joana.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Joana.Infrastructure.Migrations
{
    [DbContext(typeof(JoanaDbContext))]
    partial class JoanaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Joana.Domain.CenaProizvoda", b =>
                {
                    b.Property<int>("IdProizvod")
                        .HasColumnType("integer");

                    b.Property<int>("IdCena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdCena"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("JeAktivna")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasDefaultValue("aktivna");

                    b.HasKey("IdProizvod", "IdCena");

                    b.ToTable("CenaProizvoda");

                    b.HasData(
                        new
                        {
                            IdProizvod = 1,
                            IdCena = 1,
                            Cena = 1800.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 1,
                            IdCena = 2,
                            Cena = 1950.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 2,
                            IdCena = 1,
                            Cena = 1450.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 2,
                            IdCena = 2,
                            Cena = 1580.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 3,
                            IdCena = 1,
                            Cena = 2100.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 18, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 3,
                            IdCena = 2,
                            Cena = 2250.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 4,
                            IdCena = 1,
                            Cena = 950.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 8, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 4,
                            IdCena = 2,
                            Cena = 1020.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 5,
                            IdCena = 1,
                            Cena = 1100.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 5,
                            IdCena = 2,
                            Cena = 1180.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 6,
                            IdCena = 1,
                            Cena = 350.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 6,
                            IdCena = 2,
                            Cena = 395.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 18, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 7,
                            IdCena = 1,
                            Cena = 650.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 7,
                            IdCena = 2,
                            Cena = 720.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 8,
                            IdCena = 1,
                            Cena = 480.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 8,
                            IdCena = 2,
                            Cena = 520.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 25, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 9,
                            IdCena = 1,
                            Cena = 8700.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 9,
                            IdCena = 2,
                            Cena = 9435.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 10,
                            IdCena = 1,
                            Cena = 1950.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 14, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 10,
                            IdCena = 2,
                            Cena = 2190.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 21, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 11,
                            IdCena = 1,
                            Cena = 1250.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 11, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 11,
                            IdCena = 2,
                            Cena = 1350.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 12,
                            IdCena = 1,
                            Cena = 2700.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 12,
                            IdCena = 2,
                            Cena = 2950.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 13,
                            IdCena = 1,
                            Cena = 1600.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 13,
                            IdCena = 2,
                            Cena = 1775.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 19, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 14,
                            IdCena = 1,
                            Cena = 1800.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 14,
                            IdCena = 2,
                            Cena = 1975.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 15,
                            IdCena = 1,
                            Cena = 1900.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 13, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 15,
                            IdCena = 2,
                            Cena = 2050.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 16,
                            IdCena = 1,
                            Cena = 310.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 16,
                            IdCena = 2,
                            Cena = 350.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 17,
                            IdCena = 1,
                            Cena = 310.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 13, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 17,
                            IdCena = 2,
                            Cena = 350.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 18,
                            IdCena = 1,
                            Cena = 700.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 18,
                            IdCena = 2,
                            Cena = 790.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 19,
                            IdCena = 1,
                            Cena = 310.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 16, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 19,
                            IdCena = 2,
                            Cena = 350.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 20,
                            IdCena = 1,
                            Cena = 45.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 19, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 20,
                            IdCena = 2,
                            Cena = 50.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 24, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 21,
                            IdCena = 1,
                            Cena = 55.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 14, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 21,
                            IdCena = 2,
                            Cena = 65.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 19, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 22,
                            IdCena = 1,
                            Cena = 220.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 16, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 22,
                            IdCena = 2,
                            Cena = 245.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 23, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 23,
                            IdCena = 1,
                            Cena = 250.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 23,
                            IdCena = 2,
                            Cena = 285.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 24,
                            IdCena = 1,
                            Cena = 70.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 13, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 24,
                            IdCena = 2,
                            Cena = 79.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 18, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 25,
                            IdCena = 1,
                            Cena = 70.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 25,
                            IdCena = 2,
                            Cena = 79.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 26,
                            IdCena = 1,
                            Cena = 60.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 19, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 26,
                            IdCena = 2,
                            Cena = 69.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 24, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 27,
                            IdCena = 1,
                            Cena = 72.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 27,
                            IdCena = 2,
                            Cena = 82.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 28,
                            IdCena = 1,
                            Cena = 50.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 28,
                            IdCena = 2,
                            Cena = 60.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 21, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 29,
                            IdCena = 1,
                            Cena = 50.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 16, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 29,
                            IdCena = 2,
                            Cena = 60.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 21, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 30,
                            IdCena = 1,
                            Cena = 50.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 30,
                            IdCena = 2,
                            Cena = 60.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 31,
                            IdCena = 1,
                            Cena = 50.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 31,
                            IdCena = 2,
                            Cena = 60.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        },
                        new
                        {
                            IdProizvod = 32,
                            IdCena = 1,
                            Cena = 50.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 16, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "neaktivna"
                        },
                        new
                        {
                            IdProizvod = 32,
                            IdCena = 2,
                            Cena = 60.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JeAktivna = "aktivna"
                        });
                });

            modelBuilder.Entity("Joana.Domain.Kategorija", b =>
                {
                    b.Property<int>("IdKategorija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdKategorija"));

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdKategorija");

                    b.HasIndex("NazivKategorije")
                        .IsUnique();

                    b.ToTable("Kategorija");

                    b.HasData(
                        new
                        {
                            IdKategorija = 1,
                            NazivKategorije = "Herbicidi"
                        },
                        new
                        {
                            IdKategorija = 2,
                            NazivKategorije = "Insekticidi"
                        },
                        new
                        {
                            IdKategorija = 3,
                            NazivKategorije = "Fungicidi"
                        },
                        new
                        {
                            IdKategorija = 4,
                            NazivKategorije = "Površinska đubriva"
                        },
                        new
                        {
                            IdKategorija = 5,
                            NazivKategorije = "Prihrane"
                        },
                        new
                        {
                            IdKategorija = 6,
                            NazivKategorije = "Seme povrća"
                        },
                        new
                        {
                            IdKategorija = 7,
                            NazivKategorije = "Seme žitarica"
                        },
                        new
                        {
                            IdKategorija = 8,
                            NazivKategorije = "Seme cveća"
                        });
                });

            modelBuilder.Entity("Joana.Domain.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdKorisnik"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("IdKorisnik");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnik");

                    b.HasDiscriminator<string>("Role").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Joana.Domain.Narudzbenica", b =>
                {
                    b.Property<int>("IdNarudzbenica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdNarudzbenica"));

                    b.Property<int?>("AdministratorIdKorisnik")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DatumKreiranja")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("IdAdministrator")
                        .HasColumnType("integer");

                    b.Property<int>("IdKupac")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatusNarudzbenice")
                        .HasColumnType("integer");

                    b.Property<string>("NapomenaKupca")
                        .HasColumnType("text");

                    b.HasKey("IdNarudzbenica");

                    b.HasIndex("AdministratorIdKorisnik");

                    b.HasIndex("IdKupac");

                    b.HasIndex("IdStatusNarudzbenice");

                    b.ToTable("Narudzbenica");

                    b.HasData(
                        new
                        {
                            IdNarudzbenica = 1,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 5, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 2,
                            IdStatusNarudzbenice = 4,
                            NapomenaKupca = "Molim vas isporučiti u prepodnevnim časovima."
                        },
                        new
                        {
                            IdNarudzbenica = 2,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 8, 12, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 3,
                            IdStatusNarudzbenice = 4,
                            NapomenaKupca = "Pozvati kupca pre isporuke."
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 12, 9, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 4,
                            IdStatusNarudzbenice = 4,
                            NapomenaKupca = ""
                        },
                        new
                        {
                            IdNarudzbenica = 4,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 15, 14, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 5,
                            IdStatusNarudzbenice = 3,
                            NapomenaKupca = "Potrebno što pre."
                        },
                        new
                        {
                            IdNarudzbenica = 5,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 18, 11, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 6,
                            IdStatusNarudzbenice = 3,
                            NapomenaKupca = ""
                        },
                        new
                        {
                            IdNarudzbenica = 6,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 21, 16, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 7,
                            IdStatusNarudzbenice = 3,
                            NapomenaKupca = "Molim proveru dostupnosti proizvoda."
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 24, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 8,
                            IdStatusNarudzbenice = 2,
                            NapomenaKupca = "Isporuka na adresu kupca."
                        },
                        new
                        {
                            IdNarudzbenica = 8,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 26, 13, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 2,
                            IdStatusNarudzbenice = 2,
                            NapomenaKupca = ""
                        },
                        new
                        {
                            IdNarudzbenica = 9,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 3, 28, 10, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdKupac = 3,
                            IdStatusNarudzbenice = 2,
                            NapomenaKupca = "Pozvati pre slanja."
                        },
                        new
                        {
                            IdNarudzbenica = 10,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 4, 1, 9, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdKupac = 4,
                            IdStatusNarudzbenice = 1,
                            NapomenaKupca = ""
                        },
                        new
                        {
                            IdNarudzbenica = 11,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 4, 3, 11, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdKupac = 5,
                            IdStatusNarudzbenice = 1,
                            NapomenaKupca = "Isporuka tokom radnog vremena."
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 4, 5, 15, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdKupac = 6,
                            IdStatusNarudzbenice = 1,
                            NapomenaKupca = ""
                        },
                        new
                        {
                            IdNarudzbenica = 13,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 4, 7, 10, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdKupac = 7,
                            IdStatusNarudzbenice = 1,
                            NapomenaKupca = "Molim potvrdu narudžbenice."
                        },
                        new
                        {
                            IdNarudzbenica = 14,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 4, 9, 12, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdKupac = 8,
                            IdStatusNarudzbenice = 1,
                            NapomenaKupca = "Pozvati kupca."
                        },
                        new
                        {
                            IdNarudzbenica = 15,
                            DatumKreiranja = new DateTimeOffset(new DateTime(2026, 4, 11, 14, 25, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdKupac = 2,
                            IdStatusNarudzbenice = 1,
                            NapomenaKupca = ""
                        });
                });

            modelBuilder.Entity("Joana.Domain.ObradaNarudžbenice", b =>
                {
                    b.Property<int>("IdObrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdObrada"));

                    b.Property<DateTimeOffset>("DatumObrada")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("IdAdministrator")
                        .HasColumnType("integer");

                    b.Property<int>("IdNarudzbenica")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatusNarudzbenica")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .HasColumnType("text");

                    b.HasKey("IdObrada");

                    b.HasIndex("IdAdministrator");

                    b.HasIndex("IdNarudzbenica");

                    b.HasIndex("IdStatusNarudzbenica");

                    b.ToTable("ObradaNarudžbenice");

                    b.HasData(
                        new
                        {
                            IdObrada = 1,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 5, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 1,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 2,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 5, 13, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 1,
                            IdStatusNarudzbenica = 2,
                            Komentar = "Narudžbenica odobrena."
                        },
                        new
                        {
                            IdObrada = 3,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 7, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 1,
                            IdStatusNarudzbenica = 4,
                            Komentar = "Narudžbenica isporučena kupcu."
                        },
                        new
                        {
                            IdObrada = 4,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 8, 12, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 2,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 5,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 8, 15, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 2,
                            IdStatusNarudzbenica = 2,
                            Komentar = "Narudžbenica odobrena."
                        },
                        new
                        {
                            IdObrada = 6,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 10, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 2,
                            IdStatusNarudzbenica = 4,
                            Komentar = "Narudžbenica isporučena kupcu."
                        },
                        new
                        {
                            IdObrada = 7,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 12, 9, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 3,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 8,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 12, 12, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 3,
                            IdStatusNarudzbenica = 2,
                            Komentar = "Narudžbenica odobrena."
                        },
                        new
                        {
                            IdObrada = 9,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 14, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 3,
                            IdStatusNarudzbenica = 4,
                            Komentar = "Narudžbenica isporučena kupcu."
                        },
                        new
                        {
                            IdObrada = 10,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 15, 14, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 4,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 11,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 15, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 4,
                            IdStatusNarudzbenica = 3,
                            Komentar = "Narudžbenica odbijena zbog nedostupnosti proizvoda."
                        },
                        new
                        {
                            IdObrada = 12,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 18, 11, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 5,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 13,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 18, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 5,
                            IdStatusNarudzbenica = 3,
                            Komentar = "Narudžbenica odbijena."
                        },
                        new
                        {
                            IdObrada = 14,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 21, 16, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 6,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 15,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 22, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 6,
                            IdStatusNarudzbenica = 3,
                            Komentar = "Narudžbenica odbijena zbog nedostupnosti proizvoda."
                        },
                        new
                        {
                            IdObrada = 16,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 24, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 7,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 17,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 24, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 7,
                            IdStatusNarudzbenica = 2,
                            Komentar = "Narudžbenica odobrena."
                        },
                        new
                        {
                            IdObrada = 18,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 26, 13, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 8,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 19,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 26, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 8,
                            IdStatusNarudzbenica = 2,
                            Komentar = "Narudžbenica odobrena."
                        },
                        new
                        {
                            IdObrada = 20,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 28, 10, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdNarudzbenica = 9,
                            IdStatusNarudzbenica = 1,
                            Komentar = "Narudžbenica kreirana."
                        },
                        new
                        {
                            IdObrada = 21,
                            DatumObrada = new DateTimeOffset(new DateTime(2026, 3, 28, 13, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdAdministrator = 1,
                            IdNarudzbenica = 9,
                            IdStatusNarudzbenica = 2,
                            Komentar = "Narudžbenica odobrena."
                        });
                });

            modelBuilder.Entity("Joana.Domain.Proizvod", b =>
                {
                    b.Property<int>("IdProizvod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdProizvod"));

                    b.Property<int>("JedinicaMere")
                        .HasColumnType("integer");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("integer");

                    b.Property<int>("Lager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.HasKey("IdProizvod");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Proizvod");

                    b.HasData(
                        new
                        {
                            IdProizvod = 1,
                            JedinicaMere = 2,
                            KategorijaId = 1,
                            Lager = 10,
                            Naziv = "Corum",
                            Opis = "Corum® je jedini herbicid na tržištu formulisan specijalno za soju. Na najselektivniji na?in suzbija širokolisne korove i jednogodišnje travne korove i predstavlja kompletno rešenje za post-em tretman."
                        },
                        new
                        {
                            IdProizvod = 2,
                            JedinicaMere = 2,
                            KategorijaId = 1,
                            Lager = 10,
                            Naziv = "Glisando",
                            Opis = "Glisando je regulator rasta za sprečavanje poleganja useva pšenice* i ječma"
                        },
                        new
                        {
                            IdProizvod = 3,
                            JedinicaMere = 3,
                            KategorijaId = 1,
                            Lager = 10,
                            Naziv = "Rimex",
                            Opis = "Herbicid Rimsulfuron pripada grupi Sulfoniluree"
                        },
                        new
                        {
                            IdProizvod = 4,
                            JedinicaMere = 2,
                            KategorijaId = 1,
                            Lager = 10,
                            Naziv = "Glifomark",
                            Opis = "neselektivni herbicid, usvaja se lisnom masom. Kreće se naviše i naniže u biljci, inaktivirase u kontaktu sa zemljištem. Inhibira EPSP, odnosno sintezu aromatičnih kiselina čime sprečava sintezu neophodnih aminokiselina za proizvodnju proteina."
                        },
                        new
                        {
                            IdProizvod = 5,
                            JedinicaMere = 2,
                            KategorijaId = 1,
                            Lager = 10,
                            Naziv = "Glifol",
                            Opis = "Aktivna materija: glifosat IPA (480 g/l) Formulacija: Koncentrovani rastvor (SL) "
                        },
                        new
                        {
                            IdProizvod = 6,
                            JedinicaMere = 3,
                            KategorijaId = 2,
                            Lager = 15,
                            Naziv = "Etiol Ultra 100 ml",
                            Opis = "Insekticid za suzbijanje štetnih insekata."
                        },
                        new
                        {
                            IdProizvod = 7,
                            JedinicaMere = 3,
                            KategorijaId = 2,
                            Lager = 12,
                            Naziv = "Bros sprej protiv osa i stršljenova 400 ml",
                            Opis = "Sprej za suzbijanje osa i stršljenova."
                        },
                        new
                        {
                            IdProizvod = 8,
                            JedinicaMere = 3,
                            KategorijaId = 2,
                            Lager = 10,
                            Naziv = "Nadzor 50 ml",
                            Opis = "Preparat za zaštitu biljaka od štetočina."
                        },
                        new
                        {
                            IdProizvod = 9,
                            JedinicaMere = 2,
                            KategorijaId = 2,
                            Lager = 8,
                            Naziv = "Alverde 1 l",
                            Opis = "Insekticid sa kontaktnim i digestivnim delovanjem."
                        },
                        new
                        {
                            IdProizvod = 10,
                            JedinicaMere = 3,
                            KategorijaId = 3,
                            Lager = 10,
                            Naziv = "Olimp 0.5 l",
                            Opis = "Fungicid za zaštitu biljaka od biljnih bolesti."
                        },
                        new
                        {
                            IdProizvod = 11,
                            JedinicaMere = 2,
                            KategorijaId = 3,
                            Lager = 10,
                            Naziv = "Semesan 1 l",
                            Opis = "Preparat za zaštitu biljaka od gljivičnih oboljenja."
                        },
                        new
                        {
                            IdProizvod = 12,
                            JedinicaMere = 1,
                            KategorijaId = 3,
                            Lager = 10,
                            Naziv = "Alijansa 1 kg",
                            Opis = "Sistemični i kontaktni fungicid."
                        },
                        new
                        {
                            IdProizvod = 13,
                            JedinicaMere = 1,
                            KategorijaId = 4,
                            Lager = 20,
                            Naziv = "KAN 27% 25 kg Genezis",
                            Opis = "Azotno mineralno đubrivo za prihranu biljaka."
                        },
                        new
                        {
                            IdProizvod = 14,
                            JedinicaMere = 1,
                            KategorijaId = 4,
                            Lager = 20,
                            Naziv = "Urea 46% ruska 25 kg",
                            Opis = "Granulisano azotno đubrivo sa visokim sadržajem azota."
                        },
                        new
                        {
                            IdProizvod = 15,
                            JedinicaMere = 1,
                            KategorijaId = 4,
                            Lager = 20,
                            Naziv = "Amonijum nitrat AN Genezis 25 kg",
                            Opis = "Azotno mineralno đubrivo za osnovnu i dopunsku prihranu."
                        },
                        new
                        {
                            IdProizvod = 16,
                            JedinicaMere = 3,
                            KategorijaId = 5,
                            Lager = 15,
                            Naziv = "Blumi za orhideje 500 ml",
                            Opis = "Tečno đubrivo namenjeno prihrani orhideja."
                        },
                        new
                        {
                            IdProizvod = 17,
                            JedinicaMere = 3,
                            KategorijaId = 5,
                            Lager = 15,
                            Naziv = "Blumi za ruže 500 ml",
                            Opis = "Tečno đubrivo namenjeno prihrani ruža."
                        },
                        new
                        {
                            IdProizvod = 18,
                            JedinicaMere = 2,
                            KategorijaId = 5,
                            Lager = 10,
                            Naziv = "Foligal kalcijum 1 l",
                            Opis = "Tečno folijarno đubrivo sa kalcijumom."
                        },
                        new
                        {
                            IdProizvod = 19,
                            JedinicaMere = 3,
                            KategorijaId = 5,
                            Lager = 15,
                            Naziv = "Blumi za muškatle 500 ml",
                            Opis = "Tečno đubrivo namenjeno prihrani muškatli."
                        },
                        new
                        {
                            IdProizvod = 20,
                            JedinicaMere = 3,
                            KategorijaId = 6,
                            Lager = 30,
                            Naziv = "Seme špinat Matador",
                            Opis = "Seme špinata sorte Matador."
                        },
                        new
                        {
                            IdProizvod = 21,
                            JedinicaMere = 3,
                            KategorijaId = 6,
                            Lager = 30,
                            Naziv = "Seme tikvica Beogradska",
                            Opis = "Seme tikvice sorte Beogradska."
                        },
                        new
                        {
                            IdProizvod = 22,
                            JedinicaMere = 3,
                            KategorijaId = 6,
                            Lager = 25,
                            Naziv = "Seme boranija Maxidor 100 g",
                            Opis = "Seme boranije sorte Maxidor."
                        },
                        new
                        {
                            IdProizvod = 23,
                            JedinicaMere = 3,
                            KategorijaId = 6,
                            Lager = 25,
                            Naziv = "Beli luk domaći 200 g",
                            Opis = "Domaći beli luk za sadnju."
                        },
                        new
                        {
                            IdProizvod = 24,
                            JedinicaMere = 1,
                            KategorijaId = 7,
                            Lager = 50,
                            Naziv = "Semenska pšenica Basmati",
                            Opis = "Semenska pšenica sorte Basmati."
                        },
                        new
                        {
                            IdProizvod = 25,
                            JedinicaMere = 1,
                            KategorijaId = 7,
                            Lager = 50,
                            Naziv = "Semenska pšenica LG Avenue",
                            Opis = "Semenska pšenica sorte LG Avenue."
                        },
                        new
                        {
                            IdProizvod = 26,
                            JedinicaMere = 1,
                            KategorijaId = 7,
                            Lager = 50,
                            Naziv = "Semenski ječam Grand",
                            Opis = "Semenski ječam sorte Grand."
                        },
                        new
                        {
                            IdProizvod = 27,
                            JedinicaMere = 1,
                            KategorijaId = 7,
                            Lager = 50,
                            Naziv = "Semenska pšenica Sofru",
                            Opis = "Semenska pšenica sorte Sofru."
                        },
                        new
                        {
                            IdProizvod = 28,
                            JedinicaMere = 3,
                            KategorijaId = 8,
                            Lager = 30,
                            Naziv = "Seme cveća Petunija",
                            Opis = "Seme petunije za uzgoj ukrasnog cveća."
                        },
                        new
                        {
                            IdProizvod = 29,
                            JedinicaMere = 3,
                            KategorijaId = 8,
                            Lager = 30,
                            Naziv = "Seme cveća Dan i noć",
                            Opis = "Seme cveća dan i noć."
                        },
                        new
                        {
                            IdProizvod = 30,
                            JedinicaMere = 3,
                            KategorijaId = 8,
                            Lager = 30,
                            Naziv = "Seme cveća Noćna frajla",
                            Opis = "Seme ukrasnog cveća noćna frajla."
                        },
                        new
                        {
                            IdProizvod = 31,
                            JedinicaMere = 3,
                            KategorijaId = 8,
                            Lager = 30,
                            Naziv = "Seme cveća Goruća ljubav",
                            Opis = "Seme ukrasnog cveća goruća ljubav."
                        },
                        new
                        {
                            IdProizvod = 32,
                            JedinicaMere = 3,
                            KategorijaId = 8,
                            Lager = 30,
                            Naziv = "Seme cveća Neven",
                            Opis = "Seme nevena za uzgoj ukrasnog cveća."
                        });
                });

            modelBuilder.Entity("Joana.Domain.StatusNarudzbenice", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("NazivStatusa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusNarudzbenice");

                    b.HasData(
                        new
                        {
                            IdStatus = 1,
                            NazivStatusa = "Kreiranо"
                        },
                        new
                        {
                            IdStatus = 2,
                            NazivStatusa = "Odobreno"
                        },
                        new
                        {
                            IdStatus = 3,
                            NazivStatusa = "Odbijeno"
                        },
                        new
                        {
                            IdStatus = 4,
                            NazivStatusa = "Isporučenо"
                        });
                });

            modelBuilder.Entity("Joana.Domain.StavkaNarudzbenice", b =>
                {
                    b.Property<int>("IdNarudzbenica")
                        .HasColumnType("integer");

                    b.Property<int>("RBrProizvoda")
                        .HasColumnType("integer");

                    b.Property<int>("IdProizvod")
                        .HasColumnType("integer");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<decimal>("UgovorenaCena")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdNarudzbenica", "RBrProizvoda");

                    b.HasIndex("IdProizvod");

                    b.ToTable("StavkaNarudzbenice");

                    b.HasData(
                        new
                        {
                            IdNarudzbenica = 1,
                            RBrProizvoda = 1,
                            IdProizvod = 1,
                            Kolicina = 2,
                            UgovorenaCena = 1850m
                        },
                        new
                        {
                            IdNarudzbenica = 1,
                            RBrProizvoda = 2,
                            IdProizvod = 13,
                            Kolicina = 3,
                            UgovorenaCena = 1250m
                        },
                        new
                        {
                            IdNarudzbenica = 1,
                            RBrProizvoda = 3,
                            IdProizvod = 20,
                            Kolicina = 5,
                            UgovorenaCena = 180m
                        },
                        new
                        {
                            IdNarudzbenica = 1,
                            RBrProizvoda = 4,
                            IdProizvod = 28,
                            Kolicina = 2,
                            UgovorenaCena = 120m
                        },
                        new
                        {
                            IdNarudzbenica = 2,
                            RBrProizvoda = 1,
                            IdProizvod = 2,
                            Kolicina = 1,
                            UgovorenaCena = 2100m
                        },
                        new
                        {
                            IdNarudzbenica = 2,
                            RBrProizvoda = 2,
                            IdProizvod = 16,
                            Kolicina = 4,
                            UgovorenaCena = 350m
                        },
                        new
                        {
                            IdNarudzbenica = 2,
                            RBrProizvoda = 3,
                            IdProizvod = 24,
                            Kolicina = 10,
                            UgovorenaCena = 95m
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            RBrProizvoda = 1,
                            IdProizvod = 3,
                            Kolicina = 2,
                            UgovorenaCena = 1650m
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            RBrProizvoda = 2,
                            IdProizvod = 8,
                            Kolicina = 3,
                            UgovorenaCena = 890m
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            RBrProizvoda = 3,
                            IdProizvod = 18,
                            Kolicina = 2,
                            UgovorenaCena = 740m
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            RBrProizvoda = 4,
                            IdProizvod = 21,
                            Kolicina = 4,
                            UgovorenaCena = 160m
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            RBrProizvoda = 5,
                            IdProizvod = 26,
                            Kolicina = 15,
                            UgovorenaCena = 82m
                        },
                        new
                        {
                            IdNarudzbenica = 3,
                            RBrProizvoda = 6,
                            IdProizvod = 32,
                            Kolicina = 3,
                            UgovorenaCena = 130m
                        },
                        new
                        {
                            IdNarudzbenica = 4,
                            RBrProizvoda = 1,
                            IdProizvod = 4,
                            Kolicina = 1,
                            UgovorenaCena = 2300m
                        },
                        new
                        {
                            IdNarudzbenica = 4,
                            RBrProizvoda = 2,
                            IdProizvod = 14,
                            Kolicina = 2,
                            UgovorenaCena = 1450m
                        },
                        new
                        {
                            IdNarudzbenica = 5,
                            RBrProizvoda = 1,
                            IdProizvod = 5,
                            Kolicina = 2,
                            UgovorenaCena = 1950m
                        },
                        new
                        {
                            IdNarudzbenica = 5,
                            RBrProizvoda = 2,
                            IdProizvod = 9,
                            Kolicina = 1,
                            UgovorenaCena = 620m
                        },
                        new
                        {
                            IdNarudzbenica = 5,
                            RBrProizvoda = 3,
                            IdProizvod = 17,
                            Kolicina = 3,
                            UgovorenaCena = 360m
                        },
                        new
                        {
                            IdNarudzbenica = 5,
                            RBrProizvoda = 4,
                            IdProizvod = 23,
                            Kolicina = 4,
                            UgovorenaCena = 240m
                        },
                        new
                        {
                            IdNarudzbenica = 5,
                            RBrProizvoda = 5,
                            IdProizvod = 29,
                            Kolicina = 2,
                            UgovorenaCena = 110m
                        },
                        new
                        {
                            IdNarudzbenica = 6,
                            RBrProizvoda = 1,
                            IdProizvod = 6,
                            Kolicina = 2,
                            UgovorenaCena = 480m
                        },
                        new
                        {
                            IdNarudzbenica = 6,
                            RBrProizvoda = 2,
                            IdProizvod = 10,
                            Kolicina = 1,
                            UgovorenaCena = 910m
                        },
                        new
                        {
                            IdNarudzbenica = 6,
                            RBrProizvoda = 3,
                            IdProizvod = 15,
                            Kolicina = 3,
                            UgovorenaCena = 1380m
                        },
                        new
                        {
                            IdNarudzbenica = 6,
                            RBrProizvoda = 4,
                            IdProizvod = 31,
                            Kolicina = 5,
                            UgovorenaCena = 125m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 1,
                            IdProizvod = 1,
                            Kolicina = 1,
                            UgovorenaCena = 1850m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 2,
                            IdProizvod = 7,
                            Kolicina = 2,
                            UgovorenaCena = 430m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 3,
                            IdProizvod = 11,
                            Kolicina = 1,
                            UgovorenaCena = 760m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 4,
                            IdProizvod = 16,
                            Kolicina = 2,
                            UgovorenaCena = 350m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 5,
                            IdProizvod = 22,
                            Kolicina = 3,
                            UgovorenaCena = 290m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 6,
                            IdProizvod = 25,
                            Kolicina = 10,
                            UgovorenaCena = 98m
                        },
                        new
                        {
                            IdNarudzbenica = 7,
                            RBrProizvoda = 7,
                            IdProizvod = 30,
                            Kolicina = 2,
                            UgovorenaCena = 115m
                        },
                        new
                        {
                            IdNarudzbenica = 8,
                            RBrProizvoda = 1,
                            IdProizvod = 12,
                            Kolicina = 2,
                            UgovorenaCena = 1350m
                        },
                        new
                        {
                            IdNarudzbenica = 8,
                            RBrProizvoda = 2,
                            IdProizvod = 19,
                            Kolicina = 4,
                            UgovorenaCena = 330m
                        },
                        new
                        {
                            IdNarudzbenica = 8,
                            RBrProizvoda = 3,
                            IdProizvod = 27,
                            Kolicina = 20,
                            UgovorenaCena = 88m
                        },
                        new
                        {
                            IdNarudzbenica = 9,
                            RBrProizvoda = 1,
                            IdProizvod = 2,
                            Kolicina = 2,
                            UgovorenaCena = 2100m
                        },
                        new
                        {
                            IdNarudzbenica = 9,
                            RBrProizvoda = 2,
                            IdProizvod = 9,
                            Kolicina = 2,
                            UgovorenaCena = 620m
                        },
                        new
                        {
                            IdNarudzbenica = 9,
                            RBrProizvoda = 3,
                            IdProizvod = 18,
                            Kolicina = 3,
                            UgovorenaCena = 740m
                        },
                        new
                        {
                            IdNarudzbenica = 9,
                            RBrProizvoda = 4,
                            IdProizvod = 20,
                            Kolicina = 5,
                            UgovorenaCena = 180m
                        },
                        new
                        {
                            IdNarudzbenica = 9,
                            RBrProizvoda = 5,
                            IdProizvod = 28,
                            Kolicina = 4,
                            UgovorenaCena = 120m
                        },
                        new
                        {
                            IdNarudzbenica = 10,
                            RBrProizvoda = 1,
                            IdProizvod = 13,
                            Kolicina = 2,
                            UgovorenaCena = 1250m
                        },
                        new
                        {
                            IdNarudzbenica = 10,
                            RBrProizvoda = 2,
                            IdProizvod = 21,
                            Kolicina = 3,
                            UgovorenaCena = 160m
                        },
                        new
                        {
                            IdNarudzbenica = 11,
                            RBrProizvoda = 1,
                            IdProizvod = 4,
                            Kolicina = 1,
                            UgovorenaCena = 2300m
                        },
                        new
                        {
                            IdNarudzbenica = 11,
                            RBrProizvoda = 2,
                            IdProizvod = 8,
                            Kolicina = 2,
                            UgovorenaCena = 890m
                        },
                        new
                        {
                            IdNarudzbenica = 11,
                            RBrProizvoda = 3,
                            IdProizvod = 17,
                            Kolicina = 2,
                            UgovorenaCena = 360m
                        },
                        new
                        {
                            IdNarudzbenica = 11,
                            RBrProizvoda = 4,
                            IdProizvod = 32,
                            Kolicina = 3,
                            UgovorenaCena = 130m
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            RBrProizvoda = 1,
                            IdProizvod = 5,
                            Kolicina = 1,
                            UgovorenaCena = 1950m
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            RBrProizvoda = 2,
                            IdProizvod = 10,
                            Kolicina = 2,
                            UgovorenaCena = 910m
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            RBrProizvoda = 3,
                            IdProizvod = 14,
                            Kolicina = 2,
                            UgovorenaCena = 1450m
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            RBrProizvoda = 4,
                            IdProizvod = 23,
                            Kolicina = 3,
                            UgovorenaCena = 240m
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            RBrProizvoda = 5,
                            IdProizvod = 26,
                            Kolicina = 10,
                            UgovorenaCena = 82m
                        },
                        new
                        {
                            IdNarudzbenica = 12,
                            RBrProizvoda = 6,
                            IdProizvod = 29,
                            Kolicina = 2,
                            UgovorenaCena = 110m
                        },
                        new
                        {
                            IdNarudzbenica = 13,
                            RBrProizvoda = 1,
                            IdProizvod = 7,
                            Kolicina = 2,
                            UgovorenaCena = 430m
                        },
                        new
                        {
                            IdNarudzbenica = 13,
                            RBrProizvoda = 2,
                            IdProizvod = 15,
                            Kolicina = 1,
                            UgovorenaCena = 1380m
                        },
                        new
                        {
                            IdNarudzbenica = 13,
                            RBrProizvoda = 3,
                            IdProizvod = 31,
                            Kolicina = 4,
                            UgovorenaCena = 125m
                        },
                        new
                        {
                            IdNarudzbenica = 14,
                            RBrProizvoda = 1,
                            IdProizvod = 3,
                            Kolicina = 1,
                            UgovorenaCena = 1650m
                        },
                        new
                        {
                            IdNarudzbenica = 14,
                            RBrProizvoda = 2,
                            IdProizvod = 11,
                            Kolicina = 2,
                            UgovorenaCena = 760m
                        },
                        new
                        {
                            IdNarudzbenica = 14,
                            RBrProizvoda = 3,
                            IdProizvod = 19,
                            Kolicina = 3,
                            UgovorenaCena = 330m
                        },
                        new
                        {
                            IdNarudzbenica = 14,
                            RBrProizvoda = 4,
                            IdProizvod = 24,
                            Kolicina = 15,
                            UgovorenaCena = 95m
                        },
                        new
                        {
                            IdNarudzbenica = 14,
                            RBrProizvoda = 5,
                            IdProizvod = 30,
                            Kolicina = 2,
                            UgovorenaCena = 115m
                        },
                        new
                        {
                            IdNarudzbenica = 15,
                            RBrProizvoda = 1,
                            IdProizvod = 6,
                            Kolicina = 1,
                            UgovorenaCena = 480m
                        },
                        new
                        {
                            IdNarudzbenica = 15,
                            RBrProizvoda = 2,
                            IdProizvod = 22,
                            Kolicina = 3,
                            UgovorenaCena = 290m
                        });
                });

            modelBuilder.Entity("Joana.Domain.Administrator", b =>
                {
                    b.HasBaseType("Joana.Domain.Korisnik");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            IdKorisnik = 1,
                            Email = "uros.andjelkovic@example.com",
                            Ime = "Uroš",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Anđelković"
                        });
                });

            modelBuilder.Entity("Joana.Domain.Kupac", b =>
                {
                    b.HasBaseType("Joana.Domain.Korisnik");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Kupac");

                    b.HasData(
                        new
                        {
                            IdKorisnik = 2,
                            Email = "jovana.djokic@example.com",
                            Ime = "Jovana",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Đokić",
                            Adresa = "Bulevar kralja Aleksandra 25",
                            Grad = "Beograd",
                            Telefon = "0612345678"
                        },
                        new
                        {
                            IdKorisnik = 3,
                            Email = "jovana.stojanovic@example.com",
                            Ime = "Jovana",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Stojanović",
                            Adresa = "Futoška 42",
                            Grad = "Novi Sad",
                            Telefon = "0623456789"
                        },
                        new
                        {
                            IdKorisnik = 4,
                            Email = "dragoslav.stojanovic@example.com",
                            Ime = "Dragoslav",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Stojanović",
                            Adresa = "Vizantijski bulevar 18",
                            Grad = "Niš",
                            Telefon = "0654567890"
                        },
                        new
                        {
                            IdKorisnik = 5,
                            Email = "jovan.vukojevic@example.com",
                            Ime = "Jovan",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Vukojević",
                            Adresa = "Kralja Petra I 63",
                            Grad = "Kragujevac",
                            Telefon = "0615678901"
                        },
                        new
                        {
                            IdKorisnik = 6,
                            Email = "nikola.vuksanovic@example.com",
                            Ime = "Nikola",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Vuksanović",
                            Adresa = "Matije Korvina 11",
                            Grad = "Subotica",
                            Telefon = "0626789012"
                        },
                        new
                        {
                            IdKorisnik = 7,
                            Email = "natalija.svrkovukic@example.com",
                            Ime = "Natalija",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "SvrkoVukić",
                            Adresa = "Miloša Obrenovića 37",
                            Grad = "Pančevo",
                            Telefon = "0657890123"
                        },
                        new
                        {
                            IdKorisnik = 8,
                            Email = "milan.mladenovic@example.com",
                            Ime = "Milan",
                            LozinkaHash = "e++XzzeI5s1lsuspW+dLaw==.h/HKvS10tI474RD/8ZFjBdl+Cu41h24vGZs/5urigXQ=",
                            Prezime = "Mladenović",
                            Adresa = "Župana Stracimira 29",
                            Grad = "Čačak",
                            Telefon = "0618901234"
                        });
                });

            modelBuilder.Entity("Joana.Domain.CenaProizvoda", b =>
                {
                    b.HasOne("Joana.Domain.Proizvod", "Proizvod")
                        .WithMany("ListCenaProizvoda")
                        .HasForeignKey("IdProizvod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Joana.Domain.Narudzbenica", b =>
                {
                    b.HasOne("Joana.Domain.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorIdKorisnik");

                    b.HasOne("Joana.Domain.Kupac", "Kupac")
                        .WithMany("ListaNarudzbenica")
                        .HasForeignKey("IdKupac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joana.Domain.StatusNarudzbenice", "StatusNarudzbenice")
                        .WithMany()
                        .HasForeignKey("IdStatusNarudzbenice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Kupac");

                    b.Navigation("StatusNarudzbenice");
                });

            modelBuilder.Entity("Joana.Domain.ObradaNarudžbenice", b =>
                {
                    b.HasOne("Joana.Domain.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("IdAdministrator");

                    b.HasOne("Joana.Domain.Narudzbenica", "Narudzbenica")
                        .WithMany("ListObrada")
                        .HasForeignKey("IdNarudzbenica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joana.Domain.StatusNarudzbenice", "StatusNarudzbenica")
                        .WithMany()
                        .HasForeignKey("IdStatusNarudzbenica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Narudzbenica");

                    b.Navigation("StatusNarudzbenica");
                });

            modelBuilder.Entity("Joana.Domain.Proizvod", b =>
                {
                    b.HasOne("Joana.Domain.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("Joana.Domain.StavkaNarudzbenice", b =>
                {
                    b.HasOne("Joana.Domain.Narudzbenica", "Narudzbenica")
                        .WithMany("ListStavkeNarudzbenica")
                        .HasForeignKey("IdNarudzbenica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joana.Domain.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("IdProizvod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narudzbenica");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Joana.Domain.Narudzbenica", b =>
                {
                    b.Navigation("ListObrada");

                    b.Navigation("ListStavkeNarudzbenica");
                });

            modelBuilder.Entity("Joana.Domain.Proizvod", b =>
                {
                    b.Navigation("ListCenaProizvoda");
                });

            modelBuilder.Entity("Joana.Domain.Kupac", b =>
                {
                    b.Navigation("ListaNarudzbenica");
                });
#pragma warning restore 612, 618
        }
    }
}
